### ISSUE TITLE
Mobile - should the menu lead the page?  Shouldn't it be collapsed instead?

### ISSUE THREAD

**Issue by kelaine** [BraveUX/divorce-mediation#3]
![screen shot 2015-06-08 at 5 08 30 pm](https://cloud.githubusercontent.com/assets/9937697/8045386/0dedcf12-0e01-11e5-89c8-2def6dbc4c50.png)

**Comment by sarahkleins** [comment]
Checked with @theastralj, intro menu should be open on mobile
